### ISSUE TITLE
Unread Filter does the same thing as All Filter

### ISSUE THREAD

**Issue by KrisztianOlah** [Maledictus/LinksBag#3]
Unread filter does the same thing as All filter

Reproduce: Have links marked as read and unread and set filter to unread
Expected outcome: Only unread items are in the list.
Actual Outcome: All items in list.

**Comment by KrisztianOlah** [comment]
I believe the problem to be in filterproxymodel.cpp if a bool is in use the there are only 2 possible results true or false, if the bool is replaced by enums, a switch can be used to determine the outcome such as:

switch (MYENUM) {
case Read:
return WHATEVER;
case Unread:
return SOMETHINGELSE;
case ALL;
return BOTHWHATEVERANDSOMETHINGELSE;
}

Alternatively you can just return straight from your conditional statements.

**Comment by Maledictus** [comment]
Thx to you for your request , but I hope that I have already fixed this problem. Application will be updated today evening, I hope.
